//Tours Actions
export const LOAD_DATA_SUCCESS = "LOAD_DATA_SUCCESS";
export const CREATE_DATA_SUCCESS = "CREATE_DATA_SUCCESS";
export const UPDATE_DATA_SUCCESS = "UPDATE_DATA_SUCCESS";
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";
export const SET_TOUR_DATE_FROM = "SET_TOUR_DATE_FROM";
export const SET_TOUR_DATE_TO = "SET_TOUR_DATE_TO";

//Agent Actions
export const LOAD_AGENTS_SUCCESS = "LOAD_AGENTS_SUCCESS";
export const CREATE_AGENT_SUCCESS = "CREATE_AGENT_SUCCESS";
export const UPDATE_AGENT_SUCCESS = "UPDATE_AGENT_SUCCESS";
export const DELETE_AGENT_SUCCESS = "DELETE_AGENT_SUCCESS";

//Users Actions
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";

//API Status Actions
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

// Loyalty Actions
export const LOAD_LOYALTY_DATA_SUCCESS = "LOAD_LOYALTY_DATA_SUCCESS";
export const CREATE_LOYALTY_DATA_SUCCESS = "CREATE_LOYALTY_DATA_SUCCESS";
export const UPDATE_LOYALTY_DATA_SUCCESS = "UPDATE_LOYALTY_DATA_SUCCESS";
export const DELETE_LOYALTY_ACC_SUCCESS = "DELETE_LOYALTY_ACC_SUCCESS";

//Cards Actions
export const LOAD_CARDHOLDERS_SUCCESS = "LOAD_CARDHOLDERS_SUCCESS";
export const CREATE_CARDHOLDER_SUCCESS = "CREATE_CARDHOLDER_SUCCESS";
export const UPDATE_CARDHOLDER_SUCCESS = "UPDATE_CARDHOLDER_SUCCESS";
export const DELETE_CARDHOLDER_SUCCESS = "DELETE_CARDHOLDER_SUCCESS";

// Card Notes Actions
export const LOAD_CARD_NOTES_SUCCESS = "LOAD_CARD_NOTES_SUCCESS";
export const CREATE_CARD_NOTES_SUCCESS = "CREATE_CARD_NOTES_SUCCESS";
export const UPDATE_CARD_NOTES_SUCCESS = "UPDATE_CARD_NOTES_SUCCESS";
export const DELETE_CARD_NOTES_SUCCESS = "DELETECARD_NOTES_SUCCESS";

// Auth Actions
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT";

// Active Tab Actions
export const SET_ACTIVE_TAB_SUCCESS = "SET_ACTIVE_TAB";
export const SET_ACTIVE_TOUR_SUCCESS = "SET_ACTIVE_TOUR";
