//Tours Actions
export const LOAD_DATA_SUCCESS = "LOAD_DATA_SUCCESS";
export const CREATE_DATA_SUCCESS = "CREATE_DATA_SUCCESS";
export const UPDATE_DATA_SUCCESS = "UPDATE_DATA_SUCCESS";
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";
export const SET_TOUR_DATE_FROM = "SET_TOUR_DATE_FROM";
export const SET_TOUR_DATE_TO = "SET_TOUR_DATE_TO";

//Agent Actions
export const LOAD_AGENTS_SUCCESS = "LOAD_AGENTS_SUCCESS";
export const CREATE_AGENT_SUCCESS = "CREATE_AGENT_SUCCESS";
export const UPDATE_AGENT_SUCCESS = "UPDATE_AGENT_SUCCESS";
export const DELETE_AGENT_SUCCESS = "DELETE_AGENT_SUCCESS";

//Users Actions
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";

//API Status Actions
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

// Card Notes Actions
export const LOAD_TOUR_NOTES_SUCCESS = "LOAD_TOUR_NOTES_SUCCESS";
export const CREATE_TOUR_NOTE_SUCCESS = "CREATE_TOUR_NOTES_SUCCESS";
export const DELETE_TOUR_NOTE_SUCCESS = "DELETE_TOUR_NOTES_SUCCESS";

// Auth Actions
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT";

// Active Tab Actions
export const SET_ACTIVE_TAB_SUCCESS = "SET_ACTIVE_TAB";
export const SET_ACTIVE_TOUR_SUCCESS = "SET_ACTIVE_TOUR";
